### ISSUE TITLE
Move data directory to its own CA repo

### ISSUE THREAD

**Issue by dmundra** [GSA/open-product-accessibility-template#193]
It has useful references but can cause confusion with the catalog and other files here. We recommend moving it to its own repo maybe in CivicActions org for future reference.

**Comment by dmundra** [comment]
@mgifford what do you think?

**Comment by mgifford** [comment]
I'm fine with this. Thanks for moving over the repo @grugnog 

Rather than putting it here though:
https://github.com/CivicActions/accessibility-data-reference/pulls

I had wondered about putting under this other non-CA organization:
https://github.com/accessibility/

That said, it doesn't much matter as long as we maintain the data.
