### ISSUE TITLE
YAML to JSON and HTML research and initial addition, also prettier code formatting

### ISSUE THREAD

**Issue by dmundra** [GSA/open-product-accessibility-template#45]
Research and add YAML to JSON and HTML packages. Supporting multiple loops.

Also, add 'Prettier' code checker/formating for the codebase.

**Comment by dmundra** [comment]
For YAML to JSON found this https://github.com/nodeca/js-yaml that works well with the simple examples right now.

**Comment by dmundra** [comment]
We will likely use https://handlebarsjs.com/ to style the YAML/JSON to HTML and markdown?

**Comment by dmundra** [comment]
Remaining TODOs

- [ ] Maybe add a test for the CLI. See example https://github.com/yargs/yargs/issues/1780
- [ ] Add better error handling to the command line.
- [ ] Running YAML/JSON to HTML example using handlebarsjs.

**Comment by grugnog** [comment]
I did some thinking/research into templating options and would suggest the following as goals:

- Simple library rather than a larger framework is preferred - our needs are not complex (relative to building full websites), although having a decent library of text processing functions available with options for adding our own would be helpful (we don't need a super minimal 2kb library either)
- Supports Markdown and other text based outputs - not just HTML or web component based (e.g. React)
- Can be run in a browser as well as as a CLI
- Ideally familiar syntax for folks coming from non-JS templating language (Twig, Jinja2 etc)
- Can accept inputs with minimal processing, allowing people to use their understanding of the YAML structure to identify objects/arrays/keys etc - this also implies ability to easily drill into object structures and build nested loops

[Handlebars](https://handlebarsjs.com/) is probably the leading contender in terms of being established and familiar with a tight focus and fairly minimal dependencies - it appears to support nesting and loops also

Other options:
- [Nunchucks](https://mozilla.github.io/nunjucks/) has also been around a long time - my impression is that it has more flexibility/features than Handlebars but equally more complexity in the language
- [Squirrelly](https://squirrelly.js.org/) looks newer and has a nice plus in terms of being written in Typescript - I get the impression we would need to write a number of text filters etc ourselves though (less batteries included than the others)

Ruled out:
- Pug - HTML only
- React/Vue etc - HTML only and complex
- Underscore, EJS - too JS centric and likely unfamiliar

**Comment by mgifford** [comment]
Squirrelly is looking for a new maintainer, so worth staying away from that one. 

There are some government folks using Nunchucks for some projects, but might be useful to know if there is more use of one or another in the GSA.

**Comment by dmundra** [comment]
Thanks, @grugnog for the research into templating. I think it makes sense and we can focus on it in Sprint 2. I think we can close this after merging my small YAML to JSON PR.
