### ISSUE TITLE
Enumerate licenses of dependencies

### ISSUE THREAD

**Issue by dmundra** [GSA/open-product-accessibility-template#48]
Any included software we need to include their licenses in our license file. Automate it if possible.

**Comment by mgifford** [comment]
So would it make sense to follow the top suggestion here for including the other licenses? https://softwareengineering.stackexchange.com/questions/304874/declaring-multiple-licences-in-a-github-project

**Comment by dmundra** [comment]
Original google doc notes: https://docs.google.com/document/d/1Oi0rtesgklOwCFepLDywUvMQMyc9kIMhFYAwWngefDA/edit

**Comment by dmundra** [comment]
Found a license checker tool that can generate a text file for all dependencies. Submitted PR.

**Comment by mgifford** [comment]
Just realized we need to update this in https://github.com/GSA/open-product-accessibility-template/blob/main/LICENSE.md

Might also be useful to add something to https://github.com/GSA/open-product-accessibility-template/blob/main/license/README.md to let non-tech folks know that we've selected these tools because they are open source but that you can see all of the licenses for each project in the .txt file.

**Comment by dmundra** [comment]
Following the lead from the google doc, I think `License.md` should just speak about the OPAT software but are you thinking just a line referring to the .txt file as well?

**Comment by mgifford** [comment]
I think this would be helpful - https://github.com/GSA/open-product-accessibility-template/pull/141 - and would all we'd need to do to close this.
